# Generated by Django 3.2.6 on 2021-08-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('timeupdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='Остатки')),
                ('diagonal', models.CharField(max_length=20, verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=100, verbose_name='Разрешение')),
                ('smart_TV', models.BooleanField(default=False, verbose_name='Smart TV')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Операционная система ')),
                ('hdmi', models.CharField(max_length=10, verbose_name='Количество HDMI')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'телевизора',
                'verbose_name_plural': 'телевизора',
            },
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('timeupdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='Остатки')),
                ('volume', models.CharField(max_length=20, verbose_name='Общий полезный объем')),
                ('height', models.CharField(max_length=20, verbose_name='Высота')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('frozen_c', models.SmallIntegerField(verbose_name='Количество отделеий в морозильной камере')),
                ('no_frost', models.BooleanField(default=False, verbose_name='Система No Frost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'холодильник',
                'verbose_name_plural': 'холодильники',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('timeupdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='Остатки')),
                ('diagonal', models.CharField(max_length=20, verbose_name='Диагональ')),
                ('hdd', models.CharField(max_length=100, null=True, verbose_name='Объем жесткого диска')),
                ('processopr_freq', models.CharField(max_length=100, verbose_name='Частота процессора')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('time_work', models.CharField(max_length=20, verbose_name='Время работы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ' ноутбуки',
                'verbose_name_plural': 'ноутбук',
            },
        ),
        migrations.CreateModel(
            name='MuzCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('timeupdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='Остатки')),
                ('volume_power', models.CharField(max_length=10, verbose_name='Выходная мощность усилителя')),
                ('type', models.CharField(max_length=10, verbose_name='Тип акустики')),
                ('karaoke', models.BooleanField(default=False, verbose_name='Караоке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Музыкальный центр',
                'verbose_name_plural': 'Музыкальные центры',
            },
        ),
    ]
